
	
	<footer id = "footer">

		<div class ="section-left">
			<p class = "text-left">Proyecto TED2021-131704A-I00, WONDERCOINS financiado por MCIN/AEI/10.13039/501100011033 y por la Unión Europea “NextGenerationEU”/PRTR IP: Elena Moreno Pulido</p>
		</div>


		<div class ="section-center">
			<a class = "logo-numisdata" href="/web_numisdata/"> <img src="/web_numisdata/tpl/page/html/Logo 2 NUMISMATA_p.svg" alt=""> </a>
			<div class = "dedalo">
					<p class="dedalo_text">Powered by Dédalo 
						<a href="https://dedalo.dev" target="_blank"><img class="dedalo_image" src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/logo_dedalo_white.svg" ></a>
						Cultural Heritage Management Platform
					</p>
			</div>
		</div>
		<div class ="section-right" >
			<ul>
				<li><a href="https://administracion.gob.es/"><img src="/web_numisdata/tpl/assets/images/gob_esp.jpeg" alt=""></a></li>
				<li><a href="https://www.uca.es/"><img class="small-img" src="/web_numisdata/tpl/assets/images/logo_uca.png" alt=""></a></li>
				<li><a href="https://european-union.europa.eu/index_es"><img src="/web_numisdata/tpl/assets/images/union_europea.png" alt=""></a></li>
				<li><a href="https://planderecuperacion.gob.es/"><img src="/web_numisdata/tpl/assets/images/plan_recuperacion.png" alt=""></a></li>
			</ul>
		
		</div>

	</footer>
	
	<!-- inner 
	
	<footer class="footer">
        <img src="<?php echo __WEB_TEMPLATE_WEB__ ?>\page\html\Footer_NUMISMATA.svg" alt="Imagen de fondo del footer" class="img_fondo">
		<div class= "text-container">
		<p class="responsive-text">
		Proyecto TED2021-131704A-I00, WONDERCOINS financiado por MCIN/AEI/10.13039/501100011033 y por la Unión Europea “NextGenerationEU”/PRTR IP: Elena Moreno Pulido
        </p>
		</div>
		<div class="powered_by">

			<p class="dedalo_text">Powered by Dédalo </p>
			<a href="https://dedalo.dev" target="_blank"><img class="dedalo_image" src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/logo_dedalo_white.svg" ></a>
			<p class="dedalo_text">Cultural Heritage Management Platform</p>
			
		</div>
        <div class="logo_footer">
            <img src="<?php echo __WEB_TEMPLATE_WEB__ ?>\page\html\Logo 2 NUMISMATA_p.svg" alt="Logo Footer">
        </div>

		<div class="footer-section-wrapper" id="footer_dynamic_wraper"></div>
	</footer>
	
-->
	
