<!-- Header -->
	<header id="header">
		<div class="head_inner">

			<?php if (strpos(__WEB_ROOT_WEB__, '/pre/')!==false) { ?>
				<div class="pre_alert"></div>
			<?php } ?>

			<!-- FOR RETURN TO ANTERIOR MAIN HOME LOGO CHANGE area_name=== to "main_home" -->
			<?php /*if ($this->area_name==='main_home') { ?>

				<!-- Logo -->
					<div class="logo_big">
						<img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/logo_mib_marron.svg" alt="" />
					</div>

				<!-- Nav -->
					<nav>
						<ul>
							<li><a href="#menu"><?php echo tstring('menu') ?></a></li>
						</ul>
					</nav>

			<?php }else{ */?>

				<!-- Logo -->
		<div class="cabecera">
        <div class="header-img-container">

            <img class="header-img" src="<?php echo __WEB_TEMPLATE_WEB__ ?>/page/html/Header_NUMISMATA_prueba.svg" alt="imagen header">
			
            <div class="overlay">

			<div class="container_links">
					<ul>
						<li><a href="<?php echo __WEB_ROOT_WEB__ ?>/catalog">NUMISMÁTICA</a></li>
						<li><a href="<?php echo __WEB_ROOT_WEB__ ?>/mapas">NUMISMAPS</a></li>
						<li><a href="<?php echo __WEB_ROOT_WEB__ ?>/proyecto">PROYECTO</a></li>
					</ul> 
				</div>
				
				<div class="logo_header">
				<a class="image_link" href="<?php echo __WEB_ROOT_WEB__ ?>"><img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/page/html/Logo 1 NUMISMATA.svg" alt="Icono Numisdata"></a>
				</div>
                


				<div class="container_logosRS">
					<ul>
						<li><a href="https://x.com/HumanidadesC?t=k9ZAtacrXB4wQ5N4ECFwiQ&s=09" target="_blank"><img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/page/html/Logo X.png" alt=""></a></li>
						<li><a href="https://www.facebook.com/profile.php?id=100077890880295" target="_blank"><img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/page/html/Facebook.png" alt=""></a></li>
						<li><a href="https://www.instagram.com/humanidadesdigitalesuca?igsh=Y2piMmY5d2N6bDZ4" target="_blank"><img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/page/html/Instagram.png" alt=""></a></li>
					</ul> 
				</div>


        	</div>
		</div>
	</div>
				
				<!-- Nav -->
				<nav id="responsive-nav">
    <ul>
        <li><a href="#menu"><?php echo tstring('menu') ?></a></li>
    </ul>
</nav>

				<!-- Warning work in progress -->
					<!-- <div class="header_warning">

						<img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/Work_In_Progress.png">
						<span><?php echo tstring('work_in_progress'); // 'Work in progress. Provisional numbering. Not for citation' ?></span>

					</div>
					-->

			<?php /* } //if ($this->area_name==='main_home') { */?>
		</div>
	</header>

<!-- Menu -->
	<nav id="menu">
		<!-- lang switcher -->
			<div id="lang_globe" class="lang_globe" title="Switch lang">
				<span><?php echo tstring('lang');?></span>
				<i class="fa fa-globe"></i>
			</div>
			<ul id="page_lang_selector" class="page_lang_selector hide">
				<?php foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) { ?>
					<li class="lang_item"><a href="?lang=<?php echo $lang ?>"><?php echo $lang_name ?></a></li>
				<?php } ?>
			</ul>
		<h2><?php echo tstring('menu') ?></h2>
		<?php echo $this->menu_tree_html ?>
	</nav>
</body>
</html>
	<?php /*
	<!-- lang switcher -->
	<ul id="page_lang_selector">
		<li id="lang_globe"><i class="fa fa-globe"></i></li>
		<?php foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) { ?>
		<li><a href="?lang=<?php echo $lang ?>"><?php echo $lang_name ?></a></li>
		<?php } ?>
	</ul>
	*/ ?>