<!-- Header -->
	<header id="header">
		
				<!-- Nav -->
	<div class="container_header">

		<div><ul class="lista_enlaces">
			<li><a href="/web_numisdata/catalog">NUMISMATICA</a></li>
			<li><a href="/web_numisdata/mapas">NUMISMAPS</a></li>
			<li><a href="/web_numisdata/proyecto">PROYECTO</a></li>
		</ul></div>
		<div></div>
		<div>
			<ul class="lista_RRSS">
			<li><a href=""><img src="/web_numisdata/tpl/page/html/LogoX.png" alt=""></a></li>
			<li><a href=""><img src="/web_numisdata/tpl/page/html/Facebook.png" alt=""></a></li>
			<li><a href=""><img src="/web_numisdata/tpl/page/html/Instagram.png" alt=""></a></li>
		</div>
	</div>

				<!-- Warning work in progress -->
					<!-- <div class="header_warning">

						<img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/Work_In_Progress.png">
						<span><?php echo tstring('work_in_progress'); // 'Work in progress. Provisional numbering. Not for citation' ?></span>

					</div>
					-->

			<?php /* } //if ($this->area_name==='main_home') { */?>
		
	<nav id="responsive-nav">
    <ul>
        <li><a href="#menu"><?php echo tstring('menu') ?></a></li>
    </ul>
</nav>

	</header>

<!-- Menu -->
	<nav id="menu">
		<!-- lang switcher -->
			<div id="lang_globe" class="lang_globe" title="Switch lang">
				<span><?php echo tstring('lang');?></span>
				<i class="fa fa-globe"></i>
			</div>
			<ul id="page_lang_selector" class="page_lang_selector hide">
				<?php foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) { ?>
					<li class="lang_item"><a href="?lang=<?php echo $lang ?>"><?php echo $lang_name ?></a></li>
				<?php } ?>
			</ul>
		<h2><?php echo tstring('menu') ?></h2>
		<?php echo $this->menu_tree_html ?>
	</nav>
</body>
</html>
	<?php /*
	<!-- lang switcher -->
	<ul id="page_lang_selector">
		<li id="lang_globe"><i class="fa fa-globe"></i></li>
		<?php foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) { ?>
		<li><a href="?lang=<?php echo $lang ?>"><?php echo $lang_name ?></a></li>
		<?php } ?>
	</ul>
	*/ ?>