<?php
# REQUIRED FILES
	$base_path	= dirname(dirname(__FILE__));
	$cwd		= basename($base_path); # Current dir name

	# Cu rent controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- wrapper -->
	<div id="wrapper">
		<img id ="fondo" class ="fondo oculto " src="/web_numisdata/tpl/generic/html/Collage_op.png" alt="prueba">

		<!-- Header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>

		<!-- Main -->
			 <div id="main"> 
				<img id ="fondo2" class ="fondo oculto " src="/web_numisdata/tpl/generic/html/Icono_WonderCoins.png" alt="prueba">
				<button id ="btn-change">
					<img src="/web_numisdata/tpl/assets/images/arrow.svg" alt="arrow">
				</button>
				<div class="inner">
					<div class= "texto" id ="text">
						<div class ="image"><img src="/web_numisdata/tpl/assets/images/Logo-2-NUMISMATA_p.png" alt=""></div>
						<div class = "imagen" >
							<img src="https://wondercoins.uca.es/dedalo/media/image/1.5MB/14000/rsc29_rsc170_14629.jpg" alt="">
						</div>
						<p class ><em>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
							when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap 
							into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum 
							passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</em></p>
					</div>
					
				
				 </div>
			 </div>  

		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>
	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script src="/web_numisdata/tpl/main_home/js/change.js"></script>
