<?php
# REQUIRED FILES
	$base_path	= dirname(dirname(__FILE__));
	$cwd		= basename($base_path); # Current dir name

	# Cu rent controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- wrapper -->
	<div id="wrapper">
		<img id ="fondo" class ="fondo oculto " src="/web_numisdata/tpl/generic/html/Collage_op.png" alt="prueba">

		<!-- Header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>

		<!-- Main -->
			 <div id="main"> 
				<img id ="fondo2" class ="fondo oculto " src="/web_numisdata/tpl/generic/html/Icono_WonderCoins.png" alt="prueba">
				<button id ="btn-change">
					<img src="/web_numisdata/tpl/assets/images/arrow.svg" alt="arrow">
				</button>
				<div class="inner">
					<div class= "texto" id ="text">
						<div class ="image"><img src="/web_numisdata/tpl/assets/images/Logo-2-NUMISMATA_p.png" alt=""></div>
						<div class = "imagen" >
							<img src="/web_numisdata/tpl/main_home/css/moneda_fondo.png" alt="">
						</div>
						<p class ><em>Numisdata es un proyecto colaborativo e internacional en forma de catálogo de datos de hallazgos de monedas 
							de la Antigüedad en el occidente mediterráneo, primando la moneda en contexto arqueológico. Su objetivo es difundir y 
							estudiar el patrimonio numismático y arqueológico. Toda la información disponible en la web procede de estudios científicos 
							y está procesada por expertos. Además, ofrece un catálogo multilingüe con más de 25000 tipos antiguos, entre los que destacan 
							manuales como RRC o RIC traducidos por primera vez al castellano, francés o árabe. Los contenidos de esta web están 
							constantemente actualizados y mejorados.</em></p>
					</div>
					
				
				</div>
			 </div>  

		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>
	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script src="/web_numisdata/tpl/main_home/js/change.js"></script>
